language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - touch .env
  - mkdir -p build/logs
  - vendor/bin/phpspec run --verbose --format=dot
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
