language: php

php: 7.0

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run --verbose
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN
